apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    app: celery
spec:
  type: ClusterIP
  selector:
    app: celery
  ports:
    - port: 5555
      targetPort: flower-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      priorityClassName: app-medium-priority
      initContainers:
        - name: check-db-ready
          image: postgres:17
          command: [
              "sh",
              "-c",
              "until pg_isready -h $(POSTGRES_HOST);
              do echo waiting for postgres; sleep 2; done;",
            ]
        - name: wait-for-migrations
          image: backend:latest
          command:
            - sh
            - -c
            - |
              until python manage.py migrate --check; do
                echo "waiting for migrations to be applied";
                sleep 5;
              done
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
      containers:
        - name: celeryworker
          image: backend:latest
          command:
            - celery
          args:
            - -A
            - {{ copier__project_slug }}.celery_app
            - worker
            - -E
            - -l
            - info
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
        - name: celerybeat
          image: backend:latest
          command:
            - celery
          args:
            - -A
            - {{ copier__project_slug }}.celery_app
            - beat
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
        - name: flower
          ports:
            - name: flower-server
              containerPort: 5555
          image: backend:latest
          command:
            - celery
          args:
            - -A
            - {{ copier__project_slug }}.celery_app
            - flower
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
